export const INVALIDATE_SQUAWK = 'INVALIDATE_SQUAWK';
export const ADD_SQUAWK = 'ADD_SQUAWK';
export const UPDATE_SQUAWK = 'UPDATE_SQUAWK';
export const DELETE_SQUAWK = 'DELETE_SQUAWK';
export const GET_SQUAWK = 'GET_SQUAWK';
export const SEARCH_FOR_ONE_SQUAWK = 'SEARCH_FOR_ONE_SQUAWK';
export const SEARCH_FOR_MANY_SQUAWK = 'SEARCH_FOR_MANY_SQUAWK';
export const SELECT_SQUAWK = 'SELECT_SQUAWK';
export const LOAD_SQUAWKS = 'LOAD_SQUAWKS';
export const FETCH_SQUAWKS_BEGIN  = 'FETCH_SQUAWKS_BEGIN';
export const FETCH_SQUAWKS_SUCCESS ='FETCH_SQUAWKS_SUCESS';
export const FETCH_SQUAWKS_FAIL   = 'FETCH_SQUAWKS_FAIL';

